### ISSUE TITLE
[Suggestion]: Change REI dependency for 1.18.2 to "8.x.x"

### ISSUE THREAD

**Issue by SplendidAlakey** [Mrbysco/RoughlyEnoughProfessions#1]
### General Info

- [ ] I would like to propose new content
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

Currently, the 1.0.0 version of your mod has a hard dependency on REI 8.0.442, which makes it incompatible with REI 8.1.444 and any other future version of REI. I propose changing the dependency to 8.x.x, because 8 is a REI version number for 1.18.2 and it's probably unlikely that any future changes will break compatibility with your mod.

I tested the current version of REP with REI 8.1.444 by simply changing the REI requirement to 8.x.x fabric.mod.json and confirmed that it works as expected.

**Comment by Mrbysco** [comment]
Fixed in https://github.com/Mrbysco/RoughlyEnoughProfessions/commit/666bdeea96c22b5efb93d25db78146a6c7b27d5b

**Comment by Mrbysco** [comment]
A new version has been uploaded to CurseForge
