### ISSUE TITLE
[Suggestion]: Roughly Enough Professions 9.x

### ISSUE THREAD

**Issue by TheButterbrotMan** [Mrbysco/RoughlyEnoughProfessions#2]
### General Info

- [ ] I would like to propose new content
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

![image](https://user-images.githubusercontent.com/64548098/169679923-b088cb45-abcf-48ba-abfa-6df56012fce9.png)

**Comment by Mrbysco** [comment]
The latest Roughly Enough Professions is for 1.18 not 1.19
