### ISSUE TITLE
[Bug]: Invalid Mod Icon for Icon Source in ModMenu

### ISSUE THREAD

**Issue by nickkeane** [Mrbysco/RoughlyEnoughProfessions#4]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Fabric version

Fabric Loader 0.14.9

### Mod version

1.1.1

### Java version

Java 17

### Issue Description

REP is producing an Error when using the ModMenu.

Invalid mod icon for icon source roughlyenoughprofessions: assets/modid/icon.png

### Additional Information

Client Logs: https://pastebin.com/WAaSNp9x

**Comment by Mrbysco** [comment]
The error does absolutely nothing
