### ISSUE TITLE
[Bug]: RefMap for mixins is missing

### ISSUE THREAD

**Issue by MJRamon** [Mrbysco/RoughlyEnoughProfessions#6]
### General Info

- [ ] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

Fabric 0.14.10

### Mod version

1.1.2

### Java version

Java 17

### Issue Description

`[01:02:59] [main/WARN]: Reference map 'RoughlyEnoughProfessions-fabric-1.19-refmap.json' for roughlyenoughprofessions.mixins.json could not be read. If this is a development environment you can ignore this message`

Yes, this does not affect gameplay. Yet, this is an overview.

**Comment by Mrbysco** [comment]
This issue has been fixed in a new release that'll be available shortly
